{exec} = require 'child_process'
wrench = require 'wrench'
connect = require 'connect'
httpProxy = require 'http-proxy'

task "start", "start doing stuff", ->
	# Deep-copy an existing directory
	console.log 'Copying /src files to /target...'
	exec 'mkdir -p ../../../target/webapp'
	wrench.copyDirSyncRecursive '.', '../../../target/webapp'
	console.log 'Watching CoffeeScript files...'
	exec 'coffee --watch --compile --output ../../../target/webapp/js/ coffee/', (err, stdout, stderr) ->
	    throw err if err
	    console.log stdout + stderr

	# Redefining the "server" task for this project. Note that the output
	# displayed by --help will reflect the new task description.
	console.log 'Starting static web server in "/target/webapp" on port 3333.'

	httpProxy.createServer(5379, 'localhost').listen(8000);
	connect()
		.use(connect.static('../../../target/webapp'))
		.listen(5379);	