#
# Copyright (c) 2016 The Ontario Institute for Cancer Research. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the GNU Public License v3.0.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# DCC Submission EGA - Configuration
#

# Application
spring.application.name: dcc-submission-ega

# API
server:
  port: 8080

# Management
management:
  port: 8081

# Workspace
workspace.dir: /tmp

# Import
importer:
  retainCount: 4
  cron: 0 0 0/4 * * ?

# Banner
spring.main.banner-mode: log

ega:
  api:
      userName: # Fill in
      password: # Fill in
  ftp:
    userName: # Fill in
    password: # Fill in
  metadata:
    ftp:
      host: ftp-private.ebi.ac.uk
      user: ega-box-138
      password: tMHG3Uke
      path: /ICGC_metadata
    cron:
      data: 0 0 9,21 * * ?
      clean: 0 0 0 ? * MON
    postgresql:
      host: localhost
      database: ICGC_metadata
      user: postgres
      password: wuqiGXX57
      viewName: view_ega_sample_mapping
loader:
  db:
    username: dcc
    password: zzz123
    url: jdbc:postgresql://10.30.128.126/dcc