# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright (c) 2016 The Ontario Institute for Cancer Research. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the GNU Public License v3.0.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# DCC Submission Server - VirtualBox VM Vagrant file
#
# Description: 
#   The is the Vagrant file for provisioning the dcc-submission distribution using the 
#   VirtualBox provider and ansible as the provisioner.
#
# See:
#   - http://docs.icgc.org
#   - http://www.ansibleworks.com/docs/
#   - http://www.ansibleworks.com/docs/guide_vagrant.html
#   - http://jinja.pocoo.org/docs/templates/
#   - http://docs.vagrantup.com/v2/provisioning/ansible.html
#   - http://docs.vagrantup.com/v2/virtualbox/configuration.html

Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "precise64" 
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Hostname of the box 
  config.vm.hostname="dcc-submission-vm"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  # See provisioning/server/templates/application.conf.j2
  config.vm.network :forwarded_port, guest: 5380, host: 5380 
  config.vm.network :forwarded_port, guest: 5322, host: 5322 
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP. This IP is used in the Ansible inventory file.
  config.vm.network :private_network, ip: "10.211.55.100"
  
  # Execute VirtualBox provider
  config.vm.provider :virtualbox do |v|
  	# Appliance name
    v.name = "icgc-dcc-validator"
    
    # This should be a suitably large number for submitters to test a sample data set
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--cpus", "8"]
  end
  
  # Execute Ansible provisioner
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/vm.yml"
    ansible.inventory_path = "provisioning/inventory/hosts"
    ansible.verbose = 'vvvv'
    
    # Avoids ssh: connect to host 10.211.55.100 port 22: Host is down
    ansible.raw_arguments = "--timeout=60"
  end
end
