#!/usr/bin/python
# DCC-1925
# Constants relevant to the migration process

DONOR = "donor"
SPECIMEN = "specimen"
SAMPLE = "sample"

SSM_P = "ssm_p"

FILE_TYPES = ["cnsm_p","cnsm_s","cnsm_m","exp_g","meth_p","meth_m","mirna_p","mirna_s","mirna_m","pexp_p","pexp_m","sgv_p","sgv_m","ssm_p","ssm_m","stsm_p","stsm_s","stsm_m","donor","exp_m","jcn_p","jcn_m","meth_s","sample","specimen"] # TODO: complete


# TODO: prune
STRUCTURALLY_INVALID_ROW_ERROR ="STRUCTURALLY_INVALID_ROW_ERROR"
INVALID_CHARSET_ROW_ERROR ="INVALID_CHARSET_ROW_ERROR"
FORBIDDEN_VALUE_ERROR ="FORBIDDEN_VALUE_ERROR"
RELATION_VALUE_ERROR ="RELATION_VALUE_ERROR"
RELATION_PARENT_VALUE_ERROR ="RELATION_PARENT_VALUE_ERROR"
UNIQUE_VALUE_ERROR ="UNIQUE_VALUE_ERROR"
VALUE_TYPE_ERROR ="VALUE_TYPE_ERROR"
OUT_OF_RANGE_ERROR ="OUT_OF_RANGE_ERROR"
MISSING_VALUE_ERROR ="MISSING_VALUE_ERROR"
CODELIST_ERROR ="CODELIST_ERROR"
DISCRETE_VALUES_ERROR ="DISCRETE_VALUES_ERROR"
REGEX_ERROR ="REGEX_ERROR"
SCRIPT_ERROR ="SCRIPT_ERROR"
TOO_MANY_FILES_ERROR ="TOO_MANY_FILES_ERROR"
RELATION_FILE_ERROR ="RELATION_FILE_ERROR"
REVERSE_RELATION_FILE_ERROR ="REVERSE_RELATION_FILE_ERROR"
COMPRESSION_CODEC_ERROR ="COMPRESSION_CODEC_ERROR"
DUPLICATE_HEADER_ERROR ="DUPLICATE_HEADER_ERROR"
FILE_HEADER_ERROR ="FILE_HEADER_ERROR"
REFERENCE_GENOME_MISMATCH_ERROR ="REFERENCE_GENOME_MISMATCH_ERROR"
REFERENCE_GENOME_INSERTION_ERROR ="REFERENCE_GENOME_INSERTION_ERROR"
TOO_MANY_CONFIDENTIAL_OBSERVATIONS_ERROR ="TOO_MANY_CONFIDENTIAL_OBSERVATIONS_ERROR"

ERROR_TYPES = [ # TODO: prune
		STRUCTURALLY_INVALID_ROW_ERROR,
		INVALID_CHARSET_ROW_ERROR, 
		FORBIDDEN_VALUE_ERROR, 
		RELATION_VALUE_ERROR, 
		RELATION_PARENT_VALUE_ERROR, 
		UNIQUE_VALUE_ERROR, 
		VALUE_TYPE_ERROR, 
		OUT_OF_RANGE_ERROR, 
		MISSING_VALUE_ERROR, 
		CODELIST_ERROR, 
		DISCRETE_VALUES_ERROR, 
		REGEX_ERROR, 
		SCRIPT_ERROR, 
		TOO_MANY_FILES_ERROR, 
		RELATION_FILE_ERROR, 
		REVERSE_RELATION_FILE_ERROR, 
		COMPRESSION_CODEC_ERROR, 
		DUPLICATE_HEADER_ERROR, 
		FILE_HEADER_ERROR, 
		REFERENCE_GENOME_MISMATCH_ERROR, 
		REFERENCE_GENOME_INSERTION_ERROR, 
		TOO_MANY_CONFIDENTIAL_OBSERVATIONS_ERROR
	]

