# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2013(c) The Ontario Institute for Cancer Research. All rights reserved.
#
# DCC Submission Server - VM
#
# Description: 
#   The is the Vagrant file for provisioning the dcc-submission distribution using the 
#   VirtualBox provider and ansible as the provisioner.
#
# See:
#   - http://docs.icgc.org
#   - http://docs.vagrantup.com/v2/provisioning/ansible.html
#   - http://docs.vagrantup.com/v2/virtualbox/configuration.html

Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "precise64" 
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Hostname of the box 
  config.vm.hostname="dcc-submission-vm"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  # See provisioning/server/templates/application.conf.j2
  config.vm.network :forwarded_port, guest: 5380, host: 5380 
  config.vm.network :forwarded_port, guest: 5322, host: 5322 
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP. This IP is used in the Ansible inventory file.
  config.vm.network :private_network, ip: "10.211.55.100"
  
  # Execute VirtualBox provider
  config.vm.provider :virtualbox do |v|
    v.name = "dcc-submission-vm"
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  # Execute Ansible provisioner
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/site.yml"
    ansible.inventory_path = "provisioning/inventory/hosts"
    ansible.verbose = 'vvvv'
    ansible.raw_arguments = "--timeout=60"
  end

end
