#
# Copyright 2013(c) The Ontario Institute for Cancer Research. All rights reserved.
#
# DCC Submission Server - Application Configuration
#
# Note: 
#   The CWD will always be the bin/ directory
# See:
#   http://wrapper.tanukisoftware.com/doc/english/prop-working-dir.html

server:
  port: 5380
  
mongo:
  username: dcc-submitter
  password: HotTar3vi
  database: icgc
  host: mongodb1-dcc.res.oicr.on.ca
  uri: "mongodb://${mongo.username}:${mongo.password}@${mongo.host}/${mongo.database}?readPreference=primary"

# Root directory of DCC filesystem
fsRoot: "/icgc/submission"

# FileSystem Scheme. This sets hadoop's fs.defaultFS
fsUrl: "hdfs://hnn1-dcc.res.oicr.on.ca"

sftp:
  port : 5322
  path : "../data/sshd.pem"
  nioWorkers : 20
  # key: "<Fill in public key here, without algorithm prefix>"

hadoop: 
  # Everything set below this node ends up in the JobConf
  properties:
    "fs.defaultFS": ${fsUrl}

    # Configure the job tracker
    "mapred.job.tracker" : "hjt-dcc.res.oicr.on.ca:8021"
    "mapred.job.shuffle.input.buffer.percent" : 0.5
    "mapred.child.java.opts" : "-Xmx6g"

validator:
  maxSimultaneous: 3

# validators: ["fpv", "pv", "kv", "rgv", "nv"]
normalizer:
  errorThreshold: 1.0
  steps:
    masks.enabled: true
    duplicates.enabled: true

# If this isn't set, will pick up from the classpath by default
pcawg:
  dictionaryUrl: "file:../conf/pcawg-dictionary.json"
  sampleSheetUrl: "file:../conf/pcawg-sample-sheet.json"

reference:
  # The reference genome assembly. Assumes the existence of a .fasta.fai file in the same directory. 
  # The filename is what will be reported to users as the assembly version.
  fasta: "../data/GRCh37.fasta"

mail:
  enabled: true
  smtpHost: smtp.oicr.on.ca

  fromEmail: "no-reply@oicr.on.ca"
  supportEmail: "dcc-support@lists.oicr.on.ca"
  notificationEmail: "se-notifications@lists.oicr.on.ca"

  subject: "[DCC] Validation Finished for %s - %s!"

  errorBody: "Dear ICGC member\n\nWe have processed your submission for the project %s and the state is: %s.\n\nSince this is a system error the ICGC DCC staff has been notified and will investigate the cause. We will contact you once this error has been cleared so you can retry your submission.\n\nThe DCC team\n\nNote: this email is not monitored, for help with your submission please email ${mail.supportEmail}"
  notValidatedBody: "Dear ICGC member\n\nWe have processed your submission for the project %s and the state is: %s.\n\nThis mean that there is at least one file in your submission that has not been validated and you should now examine the summary reports on our submission site and validate the remaining files. You can find the summary reports at: https://submissions.dcc.icgc.org/releases/%s/submissions/%s. \n\nThe DCC team\n\nNote: this email is not monitored, for help with your submission please email ${mail.supportEmail}"
  invalidBody: "Dear ICGC member\n\nWe have processed your submission for the project %s and the state is: %s.\n\nThis mean that there are errors in your data and you should now examine the error reports on our submission site, fix the errors in your local submission files, re-upload these files, and try your validation again. You can find the detailed error reports at: https://submissions.dcc.icgc.org/releases/%s/submissions/%s. \n\nThe DCC team\n\nNote: this email is not monitored, for help with your submission please email ${mail.supportEmail}"
  validBody: "Dear ICGC member\n\nWe have processed your submission for the project %s and the state is: %s.\n\nSince your submission is valid it is compliant with the current ICGC data format specification. At this point you can see the summary reports at https://submissions.dcc.icgc.org/releases/%s/submissions/%s and, when ready, you can click 'signoff' on the submission portal to indicate your submission is ready for inclusion in the ICGC DCC release. If you need to make modifications to your current submission please re-upload your data and trigger the validation process again. \n\nThe DCC team\n\nNote: this email is not monitored, for help with your submission please email ${mail.supportEmail}"
  signoffBody: "Dear DCC administrator,\n\nUser %s has just signed off the submission for the project %s. This submission is ready for inclusion in the %s Data Portal release.\n\nThis message is sent out by the data validator application."
  
# A/A
auth:
  users:
    # Admin
    - {username: 'icgcdcc', password: 'tmEiwN+8', authorities: ['*'], roles: ['ADMIN']}
    
    # Submitters
    - {username: 'icgc_au', password: '3ybld32a', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_ca', password: '2AjbvRPm', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_cagekid', password: 'tf5gPS_v', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_cn', password: 'SHeM78A3', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_de', password: 'hK6PGDhR', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_es', password: 'uyqKVLwS', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_fr', password: '+9Sat1Td', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_in', password: 'Wj1b+8Pe', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_it', password: 'Pm3GtEzU', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_jp', password: 'Ts9u+L87', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_tcga', password: '4jc+szaE', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_uk', password: 'rU8j9szK', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_magic', password: 'emXe4Gtb', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_kr', password: '4iAn7bq2', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_mx', password: 'c61juwS2', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_sa', password: 'i6F3os0H', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_us', password: 'y4qZ7teo', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_target', password: 'f5+igQrA', authorities: ['release:view', 'submission:signoff']}
    - {username: 'icgc_sg', password: 'z8E+qIw2', authorities: ['release:view', 'submission:signoff']}
    - {username: 'dcc_test', password: 'n+xfJ4AU', authorities: ['release:view', 'submission:signoff']}
   
# Banner
spring.main.banner-mode: log