#!/bin/bash -e

################################################################################
# merge all files from a input directory with a single header
# Files are merged into format: <filename>.<extension>
#
# Usage:
#    ./mergefiles <dir_with_part_files> <output_file>
#
################################################################################

input=${1?} && shift
file=${1?} && shift

if [ ! -d ${input?} ]; then
   echo " Input directory ${input?} does not exist !!"
   exit
fi

echo "Output to ${file?}..."
awk 'FNR==1 && NR!=1{next;}{print}' ${input?}/* > ${file?}
