#!/bin/bash -e

################################################################################
# Split file into chunks while preserving the file header
# Files are split into format: <filename>.<number>.<extension>
#
# Usage:
#    ./splitfile <file_to_split> <number_chunks> <output_dir>
# 
################################################################################

file=${1?} && shift
chunk=${1?} && shift
output=${1?} && shift

if [ ! -f ${file?} ]; then
   echo " File ${file?} does not exist !!"
   exit 
fi

base=`basename ${file?}`

# Test
#lc=$(grep -c \n ${file?})
lc=$(grep -c ^ ${file?})
size=$(( $lc / $chunk ))
size=`expr ${size?} + 1`  # ensure not 0

echo "($lc) dividing into $chunk with $size lines per chunk"

pwd

rm -rf /tmp/splitting
mkdir /tmp/splitting
cd /tmp/splitting
tail -n +2 ${file?} | split -l ${size?} - temp_
cd -

c=0
for f in $(find /tmp/splitting -type f -name 'temp*');  do
   name=${base%.*}
   ext=${base##*.}

   dest=${output?}/${name?}.${c?}.${ext?}
   head -n 1 ${file?} > ${dest?}
   cat ${f?} >> ${dest?}
   rm ${f?}
   c=`expr ${c?} + 1`
done

