#!/bin/bash

cd $1
echo downloading metadata files ...
wget -Nrq -nH --cut-dirs=1 $2
echo $(ls -l |grep ".EGA." | wc -l) files downloaded ...
echo unzipping .tar.gz files ...
for f in *.tar.gz; do tar xfz $f; done
echo cleaning ...
rm -fr *.tar.gz